FROM node:22-bookworm

# Default to Github CI runner user.
ARG USERNAME=runner
ARG HOST_GID=1001
ARG HOST_UID=1001

RUN apt update && apt upgrade -y && \
    apt-get install -y\
    sudo\
    libnss3\
    libnspr4\
    libdbus-1-3\
    libatk1.0-0\
    libatk-bridge2.0-0\
    libcups2\
    libxcomposite1\
    libxdamage1\
    libxfixes3\
    libxrandr2\
    libgbm1\
    libxkbcommon0\
    libasound2\
    libatspi2.0-0 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN npm install -g npm@latest && \
    npm install -g pnpm && \
    pnpm --version

RUN groupadd -g ${HOST_GID} ${USERNAME} && \
    useradd -u ${HOST_UID} -g ${USERNAME} -m ${USERNAME}

# Adding the user to sudoers to make local dev en more flexible for tesing new configurations.
RUN adduser node sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER node

RUN mkdir -p /home/node/.ssh && \
    ssh-keyscan github.com >> /home/node/.ssh/known_hosts

RUN export SHELL="bash" && pnpm setup

ENV PNPM_HOME="/tmp/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

RUN SHELL="bash" && \
    pnpm config set store-dir "${PNPM_HOME}/store" && \
    pnpm install -g typescript && \
    pnpm self-update && \
    pnpm --version && tsc --version

# Required for mdx mermaid diagrams rendering    
RUN pnpx playwright-core install chromium
    
WORKDIR /tmp/workspace

CMD [ "node" ]
